import TechProps from '@/models/Tech';

export type TechMapProps = TechProps & {
	width: number;
};

export const techMap: {
	[key: string]: TechMapProps;
} = {
	html: {
		width: 50,
		className: 'object-fit',
		src: 'html',
		name: 'HTML',
		url: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
	},
	css: {
		width: 50,
		className: 'object-fit',
		src: 'css',
		name: 'CSS',
		url: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
	},
	javaScript: {
		width: 50,
		className: 'object-fit',
		src: 'javascript',
		name: 'JavaScript',
		url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide',
	},
	typescript: {
		width: 50,
		className: 'object-fit',
		src: 'typescript',
		name: 'TypeScript',
		url: 'https://www.typescriptlang.org/',
	},
	react: {
		width: 50,
		className: 'object-fit',
		src: 'react',
		name: 'React',
		url: 'https://react.dev/',
	},
	vue: {
		width: 50,
		className: 'object-fit',
		src: 'vue',
		name: 'Vue.js',
		url: 'https://vuejs.org/',
	},
	vite: {
		width: 50,
		className: 'object-fit',
		src: 'vite',
		name: 'Vite',
		url: 'https://vitejs.dev/',
	},
	next: {
		width: 50,
		className: 'object-fit',
		src: 'next',
		name: 'Next.js',
		url: 'https://nextjs.org/',
	},
	reduxToolkit: {
		width: 50,
		className: 'object-fit',
		src: 'redux',
		name: 'Redux Toolkit',
		url: 'https://redux-toolkit.js.org/',
	},
	reactRouterDom: {
		width: 50,
		className: 'object-fit',
		src: 'react-router-dom',
		// name: 'React Router Dom',
		name: 'React Router',
		url: 'https://reactrouter.com/',
	},
	reactQuery: {
		width: 50,
		className: 'object-fit',
		src: 'react-query',
		// name: 'Tanstack React Query',
		name: 'React Query',
		url: 'https://tanstack.com/query/latest',
	},
	zustand: {
		width: 50,
		className: 'object-fit',
		src: 'zustand',
		name: 'Zustand',
		url: 'https://zustand.docs.pmnd.rs/',
	},
	nodeJs: {
		width: 70,
		className: 'object-fit',
		src: 'node-js',
		name: 'Node.js',
		url: 'https://nodejs.org/en',
	},
	expressJs: {
		width: 70,
		className: 'object-fit',
		src: 'express',
		name: 'Expree.js',
		url: 'https://expressjs.com/',
	},
	mongoDb: {
		width: 80,
		className: 'object-fit',
		src: 'mongodb',
		name: 'MongoDB',
		url: 'https://www.mongodb.com/',
	},
	restApi: {
		width: 50,
		className: 'object-fit',
		src: 'rest',
		name: 'REST API',
		url: 'https://docs.github.com/en/rest',
	},
	graphQl: {
		width: 50,
		className: 'object-fit',
		src: 'graphql',
		name: 'GraphQL',
		url: 'https://graphql.org/',
	},
	axios: {
		width: 70,
		className: 'object-fit',
		src: 'axios',
		name: 'Axios HTTP',
		url: 'https://axios-http.com/docs/intro',
	},
	tailwind: {
		width: 50,
		className: 'object-fit',
		src: 'tailwind-css',
		name: 'Tailwind CSS',
		url: 'https://tailwindcss.com/',
	},
	shadCn: {
		width: 40,
		className: 'object-fit',
		src: 'shadcn',
		name: 'shadcn',
		url: 'https://ui.shadcn.com/',
	},
	materialUi: {
		width: 40,
		className: 'object-fit',
		src: 'material-ui',
		name: 'Material UI',
		url: 'https://mui.com/',
	},
	bootstrap: {
		width: 50,
		className: 'object-fit',
		src: 'bootstrap',
		name: 'Bootstrap',
		url: 'https://getbootstrap.com/',
	},
	motion: {
		width: 50,
		className: 'object-fit',
		src: 'motion',
		// name: 'Motion (formerly Framer Motion)',
		name: 'Motion',
		url: 'https://motion.dev/',
	},
	webStandards: {
		width: 50,
		className: 'object-fit',
		src: 'web-standards',
		name: 'Web Standards',
		url: 'https://www.w3.org/',
	},
	accessibility: {
		width: 50,
		className: 'object-fit',
		src: 'accessibility',
		name: 'Accessibility',
		url: 'https://www.w3.org/WAI/fundamentals/accessibility-intro/',
	},
	git: {
		width: 50,
		className: 'object-fit',
		src: 'git',
		name: 'Git',
		url: 'https://git-scm.com/',
	},
	jest: {
		width: 50,
		className: 'object-fit',
		src: 'jest',
		name: 'Jest',
		url: 'https://jestjs.io/',
	},
	mocha: {
		width: 50,
		className: 'object-fit',
		src: 'mocha',
		name: 'Mocha',
		url: 'https://mochajs.org/',
	},
	reactTestingLibrary: {
		width: 50,
		className: 'object-fit',
		src: 'react-testing-library',
		name: 'React Testing Library',
		url: 'https://testing-library.com/',
	},
	cypress: {
		width: 50,
		className: 'object-fit',
		src: 'cypress',
		name: 'Cypress',
		url: 'https://www.cypress.io/',
	},
	figma: {
		width: 40,
		className: 'object-fit',
		src: 'figma',
		name: 'Figma',
		url: 'https://www.figma.com/',
	},
	adobeCreativeCloud: {
		width: 50,
		className: 'object-fit',
		src: 'adobe-creative-cloud',
		// name: 'Adobe Creative Cloud',
		name: 'Adobe CC',
		url: 'https://creativecloud.adobe.com/',
	},
	sanity: {
		width: 70,
		className: 'object-fit',
		src: 'sanity',
		name: 'Sanity',
		url: 'https://www.sanity.io/',
	},
	wordPress: {
		width: 50,
		className: 'object-fit',
		src: 'wordpress',
		name: 'WordPress',
		url: 'https://wordpress.org/',
	},
};

export const footerTechMap: {
	[key: string]: TechMapProps;
} = {
	react: {
		width: 35,
		className: 'object-fit aspect-square',
		src: 'react',
		name: 'React',
		url: 'https://react.dev/',
	},
	reactRouterDom: {
		width: 35,
		className: 'object-fit aspect-[480/264] dark:brightness-200',
		src: 'react-router-dom',
		name: 'React Router Dom',
		url: 'https://reactrouter.com/',
	},
	reactQuery: {
		width: 35,
		className: 'object-fit aspect-[480/430]',
		src: 'react-query',
		name: 'Tanstack React Query',
		url: 'https://tanstack.com/query/latest',
	},
	axios: {
		width: 80,
		className: 'object-fit aspect-[480/73] dark:brightness-200',
		src: 'axios',
		name: 'Axios HTTP',
		url: 'https://axios-http.com/docs/intro',
	},
	motion: {
		width: 35,
		className: 'object-fit aspect-square',
		src: 'motion',
		name: 'Motion (formerly Framer Motion)',
		url: 'https://motion.dev/',
	},
	tailwind: {
		width: 35,
		className: 'object-fit aspect-[480/290]',
		src: 'tailwind-css',
		name: 'Tailwind CSS',
		url: 'https://tailwindcss.com/',
	},
	typescript: {
		width: 30,
		className: 'object-fit aspect-square',
		src: 'typescript',
		name: 'TypeScript',
		url: 'https://www.typescriptlang.org/',
	},
	vite: {
		width: 35,
		className: 'object-fit aspect-[480/481]',
		src: 'vite',
		name: 'Vite',
		url: 'https://vitejs.dev/',
	},
	nodeJs: {
		width: 60,
		className: 'object-fitaspect-[480/297] dark:brightness-200',
		src: 'node-js',
		name: 'Node.js',
		url: 'https://nodejs.org/en',
	},
	expressJs: {
		width: 60,
		className:
			'object-fit aspect-[480/144] dark:invert dark:brightness-50 dark:sepia-100 aspect-[480/430]dark:saturate-100',
		src: 'express',
		name: 'Expree.js',
		url: 'https://expressjs.com/',
	},
	mongoDb: {
		width: 80,
		className:
			'object-fit aspect-[480/126] dark:invert dark:brightness-50 dark:sepia-100 dark:saturate-100',
		src: 'mongodb',
		name: 'MongoDB',
		url: 'https://www.mongodb.com/',
	},
};
